import test from 'node:test';
import assert from 'node:assert/strict';
import {initialExploration,explorationReduce,canContinue} from '../frontend/src/exploration-state.js';

test('必填步骤阻止空白继续，返回保留回答',()=>{let s=explorationReduce(initialExploration,{type:'NEXT'});assert.equal(s.step,'situation');assert.equal(canContinue(s),false);s=explorationReduce(s,{type:'SINGLE',field:'situation',value:'change'});s=explorationReduce(s,{type:'NEXT'});assert.equal(s.step,'blockers');s=explorationReduce(s,{type:'BACK'});assert.equal(s.answers.situation,'change');});
test('多选遵守上限并可取消',()=>{let s={...initialExploration,step:'blockers'};s=explorationReduce(s,{type:'TOGGLE',field:'blockers',value:'a',max:2});s=explorationReduce(s,{type:'TOGGLE',field:'blockers',value:'b',max:2});const same=explorationReduce(s,{type:'TOGGLE',field:'blockers',value:'c',max:2});assert.equal(same,s);s=explorationReduce(s,{type:'TOGGLE',field:'blockers',value:'a',max:2});assert.deepEqual(s.answers.blockers,['b']);});
test('确认卡可保留、删除、撤销和修改',()=>{let s={...initialExploration,step:'review'};s=explorationReduce(s,{type:'CARD',id:'human',value:'confirmed'});assert.equal(s.cards.human,'confirmed');s=explorationReduce(s,{type:'CARD',id:'human',value:'deleted'});assert.equal(s.cards.human,'deleted');s=explorationReduce(s,{type:'CARD',id:'human',value:'pending'});s=explorationReduce(s,{type:'EDIT',id:'human',value:'更准确的表达'});assert.equal(s.cards.human,'modified');assert.equal(s.edits.human,'更准确的表达');});
test('理解确认必须逐条处理后才能继续',()=>{let s={...initialExploration,step:'review'};assert.equal(canContinue(s),false);for(const id of Object.keys(s.cards))s=explorationReduce(s,{type:'CARD',id,value:id==='unknown'?'deleted':'confirmed'});assert.equal(canContinue(s),true);assert.equal(explorationReduce(s,{type:'NEXT'}).step,'result');});
test('修改回答会让旧确认失效并阻止直接进入结果',()=>{let s={...structuredClone(initialExploration),step:'review',cards:{experience:'confirmed',human:'modified',ability:'deleted',unknown:'confirmed'},edits:{human:'旧修改'}};s=explorationReduce(s,{type:'SINGLE',field:'experience',value:'work'});assert.deepEqual(s.cards,{experience:'pending',human:'pending',ability:'deleted',unknown:'pending'});assert.deepEqual(s.edits,{});assert.equal(canContinue(s),false);});
test('分析支持加载、失败、重试、取消且保留回答',()=>{const answerState={...initialExploration,step:'outcome',answers:{...initialExploration.answers,outcomes:['artifact']}};let s=explorationReduce(answerState,{type:'ANALYSIS_START'});assert.equal(s.analysisStatus,'loading');s=explorationReduce(s,{type:'ANALYSIS_FAIL',error:'暂时无法完成分析'});assert.equal(s.analysisStatus,'error');s=explorationReduce(s,{type:'ANALYSIS_START'});s=explorationReduce(s,{type:'ANALYSIS_CANCEL'});assert.equal(s.step,'outcome');assert.deepEqual(s.answers.outcomes,['artifact']);});
test('地图更新只能在预览页保存或仅本次使用，失败留在原页',()=>{const preview={...initialExploration,step:'preview'};const applied=explorationReduce(preview,{type:'APPLY_UPDATE'});assert.equal(applied.step,'done');assert.equal(applied.updateStatus,'applied');assert.equal(explorationReduce(applied,{type:'APPLY_UPDATE'}),applied);const failed=explorationReduce(preview,{type:'APPLY_FAIL'});assert.equal(failed.step,'preview');assert.equal(failed.updateStatus,'failed');const skipped=explorationReduce(preview,{type:'SKIP_UPDATE'});assert.equal(skipped.updateStatus,'session_only');});

test('重新分析保留删除，只有撤销才重新出现',()=>{let s={...structuredClone(initialExploration),step:'review',cards:{...initialExploration.cards,ability:'deleted'}};s=explorationReduce(s,{type:'BACK'});s=explorationReduce(s,{type:'ANALYSIS_START'});assert.equal(s.cards.ability,'deleted');s=explorationReduce(s,{type:'ANALYSIS_SUCCESS'});s=explorationReduce(s,{type:'CARD',id:'ability',value:'pending'});assert.equal(s.cards.ability,'pending');});
test('修改有依据的条目会让依赖关联回到待确认',()=>{const s={...initialExploration,step:'review',cards:{experience:'confirmed',ability:'confirmed',unknown:'deleted'},edits:{}};const next=explorationReduce(s,{type:'EDIT',id:'experience',value:'改写',dependentIds:['ability']});assert.equal(next.cards.experience,'modified');assert.equal(next.cards.ability,'pending');assert.equal(next.cards.unknown,'deleted');});
