import test from 'node:test';
import assert from 'node:assert/strict';
import {createPrototypeProfile} from '../frontend/src/exploration-domain.js';
import {storageKey,loadExplorationProfile,saveExplorationProfile,removeLocalEvidence} from '../frontend/src/exploration-storage.js';

function memoryStorage(){const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};}
const validEvidence={id:'one',title:'一段实践',experience:'参与一次项目',actions:['整理信息'],result:'形成成果',source:null,limitations:['仍需更多验证'],source_type:'user_self_report',confirmation_status:'confirmed'};
test('本地档案以版本信封保存并可读取',()=>{const storage=memoryStorage(),profile=createPrototypeProfile();profile.evidence.one=structuredClone(validEvidence);assert.equal(saveExplorationProfile(storage,profile).ok,true);assert.equal(JSON.parse(storage.getItem(storageKey)).kind,'user_local');assert.deepEqual(loadExplorationProfile(storage).profile,profile);});
test('旧版或损坏数据安全降级为空档案',()=>{const storage=memoryStorage();storage.setItem(storageKey,'{"version":0}');const result=loadExplorationProfile(storage);assert.equal(result.ok,false);assert.deepEqual(result.profile,createPrototypeProfile());});
test('悬空关联、错误字段和重复变更集的档案会被拒绝',()=>{const storage=memoryStorage();const profile=createPrototypeProfile();profile.evidence.one=structuredClone(validEvidence);profile.capitalLinks.bad={id:'bad',evidence_id:'missing',capital:'human',aspect:'行动',explanation:'说明',confirmation_status:'confirmed'};storage.setItem(storageKey,JSON.stringify({version:1,kind:'user_local',profile}));assert.equal(loadExplorationProfile(storage).ok,false);const duplicate={...createPrototypeProfile(),evidence:{one:structuredClone(validEvidence)},appliedChangeSets:['change_x','change_x']};storage.setItem(storageKey,JSON.stringify({version:1,kind:'user_local',profile:duplicate}));assert.equal(loadExplorationProfile(storage).ok,false);});
test('保存失败不伪报成功',()=>{const storage={getItem:()=>null,setItem:()=>{throw new Error('quota');}};assert.equal(saveExplorationProfile(storage,createPrototypeProfile()).ok,false);});
test('删除证明同步清理资本与河流关联',()=>{const profile=createPrototypeProfile();profile.evidence.one={id:'one'};profile.capitalLinks.cap={id:'cap',evidence_id:'one'};profile.riverLinks.river={id:'river',evidence_id:'one'};profile.unknowns.unknown={id:'unknown'};const next=removeLocalEvidence(profile,'one');assert.deepEqual(next.evidence,{});assert.deepEqual(next.capitalLinks,{});assert.deepEqual(next.riverLinks,{});assert.ok(next.unknowns.unknown);assert.ok(profile.evidence.one);});
