import {personalMap} from './personal-map.js';
import {profileWithGrowth,growthEvidenceId} from './growth-proof.js';
import {workspaceConnection,readActiveWorkspace as readWorkspace} from './workspace-connection.js';
import {guardWorkspaceWrite} from './workspace-feedback.js';
import {localProofFromProfile} from './local-proof.js';
import * as demoData from './data.js';
import {initial,reduce} from './state.js';
import {mapMarkup} from './map.js';
import {browserStorage} from './exploration-storage.js';
import {explorationProfileConnection} from './exploration-connection.js';

const symbols={leaf:'M20 3C9 1 3 8 5 17c7 5 16-2 15-14ZM4 21 17 7M8 16l-1-5m5 1 5-1',home:'m3 11 9-8 9 8M5 10v11h5v-7h4v7h5V10',compass:'M12 2v4m0 12v4M2 12h4m12 0h4M5 5l3 3m8 8 3 3M5 19l3-3m8-8 3-3M7 12a5 5 0 1 0 10 0 5 5 0 1 0-10 0Zm3 2 1-4 3-1-1 4Z',fork:'M12 22V3m0 9 7-5m-7 10-7-5M17 4h3v4M3 9h3v4',plan:'M6 4H4v18h16V4h-2M8 2h8v4H8Zm0 9h8m-8 4h5',chart:'M4 21V11m6 10V6m6 15V2m5 19H1',heart:'M12 21 3 11C-2 4 7-1 12 6c5-7 14-2 9 5Z',sprout:'M12 22V11M12 15C5 17 2 10 3 7c6-1 10 3 9 8ZM12 11C11 5 17 2 22 3c1 6-4 9-10 8Z',mountain:'m1 21 8-13 8 13Zm11-6 5-12 7 18h-7',arrow:'M4 12h16m-6-6 6 6-6 6',close:'m6 6 12 12M6 18 18 6',pause:'M8 5v14M16 5v14',play:'m8 4 12 8-12 8Z',replay:'M4 8A9 9 0 1 1 3 14M4 2v6h6',info:'M12 10v7m0-11v1M2 12a10 10 0 1 0 20 0 10 10 0 1 0-20 0',chevron:'m9 5 7 7-7 7',book:'M3 4h7l2 2 2-2h7v16h-7l-2 2-2-2H3Zm9 2v16',settings:'M4 7h16M4 17h16M8 3v8m8 2v8'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${symbols[name]||symbols.info}"/></svg>`;
const pos=([x,y])=>`left:${x/1672*100}%;top:${y/941*100}%`;
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const readLocalData=()=>{const workspace=readWorkspace(browserStorage()).data,explorationProfile=explorationProfileConnection.readActive().profile;return {workspace,explorationProfile,profile:profileWithGrowth(explorationProfile,workspace)};};
let {profile:localProfile,explorationProfile,workspace:localWorkspace}=readLocalData();
const demo=new URLSearchParams(location.search).get('demo')==='1';
let {rivers,proofs,directions}=demo?demoData:personalMap(localProfile,localWorkspace);
const riverById=id=>rivers.find(r=>r.id===id),proofById=id=>proofs.find(p=>p.id===id),directionById=id=>directions.find(d=>d.id===id);
const localEvidence=id=>localProfile.evidence[id]??null;
const localProof=id=>localProofFromProfile(localProfile,id);
const hasPersonalRecords=()=>proofs.length+rivers.reduce((sum,r)=>sum+(r.paths?.length??0)+(r.plans?.length??0),0)>0;
const primaryRiver=()=>rivers.find(r=>r.paths?.length||r.plans?.length)||rivers.find(r=>r.proofs.length||r.directions.length)||riverById('ability')||rivers[0];
let state={...initial},returnFocus=null,hoverTimer=null,introTimer=null,previewKey='',panelKey='',paused=false,reduceByChoice=false;
const media=window.matchMedia('(prefers-reduced-motion: reduce)');
const reduced=()=>media.matches||reduceByChoice;
const app=document.querySelector('#app');
const workspaceNode=(river,item,kind)=>`<a class="map-node workspace-map-node ${kind}-map-node node-${river.id}" style="${pos(item.point)};--river-accent:${river.color}" data-river="${river.id}" data-hover-river="${river.id}" href="/?view=${kind==='path'?'paths':'plans'}&item=${encodeURIComponent(item.id)}" aria-label="查看${kind==='path'?'路径':'计划'}：${item.name}"><span class="node-dot"></span><span class="node-caption">${kind==='path'?'路径':'计划'} · ${item.name}</span></a>`;
app.innerHTML=`<a class="skip-link" href="#map-summary">跳至地图文字说明</a><main class="shell"><div class="coordinate-space"><img class="terrain" src="/assets/three-rivers/terrain-v1.png" alt="" fetchpriority="high">${mapMarkup(directions)}<div class="map-labels">${rivers.map(r=>`<button id="river-${r.id}" class="river-label label-${r.id}" style="${pos(r.label)};--river-accent:${r.color}" data-select-river="${r.id}" data-hover-river="${r.id}" aria-label="${r.name}，${r.short}，查看摘要" aria-expanded="false"><span class="label-top"><span class="river-symbol">${icon(r.icon)}</span><span><strong>${r.name}</strong><small>${r.short}</small></span>${icon('chevron')}</span><span class="label-bottom">${r.proofs.length} 个证明 <i>·</i> ${r.status}</span></button>${(demo?r.proofs:[]).map(id=>{const p=proofById(id);return `<button id="node-${demo?p.id:r.id+'-'+p.id}" class="map-node node-${r.id}" style="${pos(p.point)};--river-accent:${r.color}" data-proof="${p.id}" data-river="${r.id}" data-hover-river="${r.id}" aria-label="查看证明：${p.title}"><span class="node-dot"></span><span class="node-caption">${p.caption.replace('\n','<br>')}</span></button>`}).join('')}${demo?'':r.paths.map(item=>workspaceNode(r,item,'path')).join('')+r.plans.map(item=>workspaceNode(r,item,'plan')).join('')}`).join('')}<span class="map-note note-love">更大的热爱<br>正在前方 <span>⟶</span></span><span class="map-note note-ability">更强大的自己<br>正在生长 <span>⟶</span></span></div></div>
<aside class="sidebar"><a class="brand" href="/">${icon('leaf')}<span>人生护城河</span></a><nav aria-label="主导航"><a class="nav-item active" href="/?view=river" aria-current="page">${icon('home')}<span>我的河</span></a><a class="nav-item" href="/?view=explore">${icon('compass')}<span>探索</span></a><a class="nav-item" href="/?view=paths">${icon('fork')}<span>未来路径</span></a><a class="nav-item" href="/?view=plans">${icon('plan')}<span>护城河计划</span></a><a class="nav-item" href="/?view=growth">${icon('chart')}<span>成长记录</span></a></nav><div class="sidebar-bottom"><span class="landscape-avatar" aria-hidden="true"></span><p>让人生<br>有更多可能的河流</p><button class="subtle-button" data-panel="settings">${icon('settings')} 显示设置</button><a class="subtle-button" href="/?view=sync">${icon('settings')} 数据与同步</a></div></aside>
<header class="page-header"><h1>我的三河地图</h1><p>每一段经历，都是让你更自由的河流。</p></header><div class="top-tools"><button class="demo-badge" data-panel="about"><span></span>关于地图 ${icon('info')}</button></div><p class="map-quote">三条河，<br><span>汇成更完整的我。</span></p>
<div class="mobile-rivers" aria-label="选择一条河">${rivers.map(r=>`<button id="mobile-${r.id}" data-select-river="${r.id}">${icon(r.icon)}${r.name}</button>`).join('')}</div>
<div id="preview" class="river-preview" hidden></div><section id="detail-panel" class="detail-panel" aria-label="地图详情" hidden></section>
<section class="action-area" aria-label="下一步"><div class="action-card"><span class="action-symbol">${icon('compass')}</span><div><h2>${!demo&&!hasPersonalRecords()?'从一段经历开始':'读懂你的一段河流'}</h2><p>从一段经历，看见积累的线索。</p>${!demo&&!hasPersonalRecords()?`<a class="primary-button" href="/?view=explore">开始探索 ${icon('arrow')}</a>`:`<button class="primary-button" data-primary-river>看看河流 ${icon('arrow')}</button>`}</div></div><button class="secondary-card" data-primary-future><span class="action-symbol small">${icon('fork')}</span><span><strong>看看未来方向</strong><small>已有支持，还有哪些待探索</small></span>${icon('chevron')}</button></section>
<footer class="status-bar"><div class="status-intro"><span class="status-dot"></span><div><strong>${demo?'独立案例':'已确认的个人记录'}</strong><small>从经历中看见支撑与可能</small></div></div><div class="stat"><small>已记录</small><strong>${proofs.length} 个证明</strong></div><div class="stat"><small>已看见</small><strong>3 条主河</strong></div><button class="text-button summary-button" id="map-summary" data-panel="summary">${icon('book')} 地图文字说明</button><div class="motion-controls"><button id="motion-toggle" class="icon-button" aria-label="暂停雾与地图动态" title="暂停动态">${icon('pause')}</button><button id="replay" class="icon-button" aria-label="重播地图显现" title="重播显现">${icon('replay')}</button></div></footer><button id="skip-intro" class="skip-intro" hidden>立即查看地图 ${icon('arrow')}</button><div id="announcement" class="sr-only" role="status" aria-live="polite"></div></main>`;
const shell=document.querySelector('.shell'),preview=document.querySelector('#preview'),panel=document.querySelector('#detail-panel');
document.querySelector('.motion-controls').insertAdjacentHTML('beforeend',`<button class="icon-button" data-panel="settings" aria-label="地图显示设置" title="显示设置">${icon('settings')}</button>`);
document.querySelectorAll('[data-system]').forEach(group=>group.querySelectorAll('.tributary').forEach((branch,i)=>{const source=demo?demoData.branchAssociations[group.dataset.system][i]:null;if(!source)return;branch.dataset.capital=source.capital;branch.dataset.proof=source.proof;branch.dataset.aspect=source.aspect;}));
function announce(message){document.querySelector('#announcement').textContent=message;}
function dispatch(action){state=reduce(state,action,{resolveProof:id=>localProof(id)||proofById(id),resolveRiver:riverById,resolveDirection:directionById});sync();}
const workspaceRecords=r=>demo?'':`<section class="river-workspace-records"><h3>这条河的工作区</h3>${r.paths.map(path=>`<a href="/?view=paths&item=${encodeURIComponent(path.id)}"><span>路径</span>${path.name} ${icon('arrow')}</a>`).join('')}${r.plans.map(plan=>`<a href="/?view=plans&item=${encodeURIComponent(plan.id)}"><span>计划</span>${plan.name} ${icon('arrow')}</a>`).join('')}${r.paths.length||r.plans.length?'':`<p class="muted">还没有保存路径或计划。</p><a href="/?view=paths&river=${r.id}"><span>路径</span>新建路径 ${icon('arrow')}</a>`}</section>`;
function previewContent(r){return `<div class="preview-heading"><span class="eyebrow">河流摘要 · ${demo?'演示':'我的记录'}</span><button class="icon-button" data-close aria-label="关闭河流摘要">${icon('close')}</button></div><h2>${r.name}</h2>${demo?'':`<p class="river-record-count">${r.proofs.length} 个证明 · ${r.paths.length} 条路径 · ${r.plans.length} 个计划</p>`}<p>${r.summary}</p><div class="chips">${r.capital.map(c=>`<span>${c}</span>`).join('')}</div><p class="muted">${r.unknown}</p>${workspaceRecords(r)}<div class="preview-actions">${r.proofs.length?`<button class="text-button" data-proof="${r.proofs[0]}" data-river="${r.id}">查看证明 ${icon('arrow')}</button>`:'<a class="text-button" href="/?view=explore">从一段经历开始 →</a>'}<button class="text-button" data-future="${r.id}" aria-expanded="false">未来方向 ${icon('fork')}</button></div>`;}
const panelHeader=(eyebrow,title)=>`<div class="panel-top"><span class="eyebrow">${eyebrow}</span><button class="icon-button" data-close aria-label="关闭详情">${icon('close')}</button></div><h2 tabindex="-1" id="detail-title">${title}</h2>`;
function panelContent(){
 if(state.panel==='local-proofs')return panelHeader('本地保存','我的探索证明')+(Object.values(localProfile.evidence).map(e=>`<p><button class="text-button" data-proof="${escapeHtml(e.id)}">${escapeHtml(e.title)} ${icon('arrow')}</button></p>`).join('')||'<p>还没有本地保存的证明。</p>');
 if(state.panel==='proof'){const local=localProof(state.proof),isLocal=Boolean(local),p=isLocal?local:proofById(state.proof);return panelHeader(isLocal?'证明详情 · 本地保存':'证明详情 · 合成示例',p.title)+`<p class="detail-meta">${p.type} · ${p.date}</p><blockquote>${p.excerpt}</blockquote><dl><dt>我的贡献</dt><dd>${p.contribution}</dd><dt>它说明了什么</dt><dd>${p.result}</dd><dt>支撑的资本</dt><dd>${p.capital}</dd>${isLocal?`<dt>河流关联依据</dt><dd>${p.riverExplanation}</dd>`:''}<dt>来源与确认状态</dt><dd>${p.source}</dd><dt>仍需补充</dt><dd>${p.limit}</dd></dl>${state.river?`<button class="primary-button" data-future="${state.river}">看看这条河的未来 ${icon('arrow')}</button>`:'<p class="muted">未保留河流关联。</p>'}${isLocal&&p.id.startsWith('growth_')?`<a class="text-button" href="/?view=growth&item=${encodeURIComponent(p.id.slice(7))}">回看原成长记录 →</a>`:''}${isLocal?'<button class="text-button" data-panel="local-proofs">查看全部本地证明</button><button class="text-button danger-button" data-delete-local>删除这条本地证明</button>':''}`;}
 if(!demo&&state.panel==='future'){const r=riverById(state.river);return panelHeader(r.name+' · 未来方向','把方向留给实践验证')+r.directions.map(id=>{const d=directionById(id);return `<section><h3>${d.name}</h3><dl><dt>已有支持</dt><dd>${d.support}</dd><dt>待验证</dt><dd>${d.gap}</dd><dt>下一步</dt><dd>${d.next}</dd></dl><a class="primary-button" href="/?view=paths&direction=${encodeURIComponent(d.id)}">核对并建立路径 →</a></section>`;}).join('')+(r.directions.length?'':'<p>这条河还没有保存的候选方向，可以继续探索或自己写一条路径。</p>')+`<p><a class="text-button" href="/?view=paths&river=${r.id}">查看这条河下的路径 →</a></p>`;}
 if(state.panel==='future'){const r=riverById(state.river),d=directionById(state.direction);return panelHeader(`${r.name} · 未来方向`,r.directions.length?'方向，留给实践来回答':'前方，还留着可能')+(d?`<p class="muted">以下为合成案例的候选方向，尚未确认或保存。</p><div class="direction-tabs" aria-label="候选方向">${r.directions.map(id=>`<button data-direction="${id}" aria-pressed="${id===d.id}">${directionById(id).name}</button>`).join('')}</div><dl><dt>已有的支持</dt><dd>${d.support}</dd><dt>尚待探索</dt><dd>${d.gap}</dd><dt>可以验证的一小步</dt><dd>${d.next}</dd></dl><button class="text-button" data-proof="${r.proofs[0]}" data-river="${r.id}">回看支撑它的证明 ${icon('arrow')}</button>`:`<p>这条河还没有已确认的候选方向。未知的部分可以慢慢探索。</p><p class="muted">先看看已有的兴趣与经历，再决定愿意投入什么。收起此视图不会删除任何内容。</p><button class="primary-button" data-proof="${r.proofs[0]}" data-river="${r.id}">从已有证明开始 ${icon('arrow')}</button>`);}
 if(!demo&&state.panel==='summary')return panelHeader('地图文字说明','三条河，三种观察角度')+`<p>已保存 ${proofs.length} 个证明、${localWorkspace.paths.length} 条路径和 ${localWorkspace.plans.length} 个计划。河道沿用当前构图，宽度不代表个人分数。</p>${rivers.map(r=>`<section class="summary-river"><h3>${r.name}</h3><p>${r.summary}</p>${r.proofs.map(id=>`<p><button class="text-button" data-proof="${id}" data-river="${r.id}">${proofById(id).title} →</button></p>`).join('')}${workspaceRecords(r)}<button class="text-button" data-future="${r.id}">查看未来方向 →</button></section>`).join('')}`;
 if(state.panel==='summary'){return panelHeader('地图文字说明','三条河，三种观察角度')+`<p class="muted">3 个合成证明 · 5 类资本框架。河道宽度是演示构图，不代表分数。</p>${rivers.map(r=>`<section class="summary-river"><h3>${r.name}</h3><p>${r.summary}</p><p class="muted">${r.unknown}</p><button class="text-button" data-proof="${r.proofs[0]}" data-river="${r.id}">${proofById(r.proofs[0]).title} ${icon('arrow')}</button><button class="text-button" data-future="${r.id}">查看未来方向 ${icon('fork')}</button></section>`).join('')}<p class="muted">浅雾表示未知或尚未探索。财务、身体资本的相关条件未提供，保持未知。</p>`;}
 if(state.panel==='settings'){return panelHeader('显示设置','让地图按你的节奏流动')+`<p>可以暂停雾与地图的环境动态，也可以重播地图显现。暂停不会影响任何信息和操作。</p><button class="primary-button" data-toggle-motion>${paused?'恢复环境动态':'暂停环境动态'} ${icon(paused?'play':'pause')}</button><button class="text-button" data-replay>重播地图显现 ${icon('replay')}</button><button class="text-button" data-reduce aria-pressed="${reduceByChoice}">${reduceByChoice?'关闭':'开启'}减少动态效果</button><p class="muted">${media.matches?'系统已开启减少动态效果，地图直接显示完整状态。':reduceByChoice?'已关闭显现、流纹、雾呼吸和位移过渡，信息保持完整。':'地图也会遵循系统的“减少动态效果”偏好。'}</p>`;}
 if(!demo)return panelHeader('关于这张地图','让记录回到自己的河流')+'<p>摘要与证明来自你在当前浏览器保存的确认内容。尚未提供的信息保持未知。</p><p>地图沿用当前视觉构图，不据此推断资本强弱；记录尚未同步到账号或云端。</p>';
 return panelHeader('关于这张地图','先看见一种可能')+`<p>这是用于验证地图体验的合成案例，所有经历、证明与方向都属于示例，不描述你的真实情况。</p><p>现在可以选择河流、阅读证明、查看未来方向和调整动态效果。</p><p class="muted"><a href="/?view=river">返回我的河 →</a></p><button class="text-button" data-panel="summary">阅读地图文字说明 ${icon('arrow')}</button>`;
}
function sync(){
 if(!demo){({rivers,proofs,directions}=personalMap(localProfile,localWorkspace));document.querySelector('.stat strong').textContent=proofs.length+' 个证明';for(const r of rivers){document.querySelector('#river-'+r.id+' .label-bottom').textContent=`${r.proofs.length} 证明 · ${r.paths.length} 路径 · ${r.plans.length} 计划`;}document.querySelectorAll('[data-proof].map-node').forEach(n=>{if(!localProfile.evidence[n.dataset.proof])n.remove();});}
 const primary=primaryRiver();document.querySelector('[data-primary-river]')?.setAttribute('data-select-river',primary.id);document.querySelector('[data-primary-future]')?.setAttribute('data-future',primary.id);

 const active=state.panel&&state.river?state.river:state.preview||state.river;
 shell.dataset.active=active||'';shell.dataset.panel=state.panel||'';
 document.querySelectorAll('[data-system]').forEach(el=>{el.classList.toggle('emphasized',el.dataset.system===active);el.classList.toggle('subdued',Boolean(active)&&el.dataset.system!==active);});
 document.querySelectorAll('.map-node[data-river]').forEach(el=>{el.classList.toggle('river-active',el.dataset.river===active);el.classList.toggle('river-subdued',Boolean(active)&&el.dataset.river!==active);});
 document.querySelectorAll('.river-label').forEach(el=>{el.setAttribute('aria-expanded',String(active===el.dataset.selectRiver));el.classList.toggle('selected',active===el.dataset.selectRiver);});
 const nextPreview=!state.panel?active:null;preview.hidden=!nextPreview;
 if(nextPreview&&previewKey!==nextPreview){preview.innerHTML=previewContent(riverById(nextPreview));previewKey=nextPreview;}
 if(!nextPreview)previewKey='';
 preview.dataset.river=nextPreview||'';
 panel.hidden=!state.panel;const key=[state.panel,state.proof,state.direction,state.river,state.panel==='settings'?`${paused}-${reduced()}`:''].join(':');
 if(state.panel&&panelKey!==key){panel.innerHTML=panelContent();panel.setAttribute('aria-labelledby','detail-title');panel.scrollTop=0;panelKey=key;}if(!state.panel)panelKey='';
 document.querySelectorAll('.map-node').forEach(el=>el.classList.toggle('selected',state.proof===el.dataset.proof));
 document.querySelector('.action-area').hidden=Boolean(state.panel||nextPreview);
 document.querySelectorAll('[data-future]').forEach(el=>el.setAttribute('aria-expanded',String(state.panel==='future'&&el.dataset.future===state.river)));
}
function close(){const hadPanel=Boolean(state.panel);dispatch({type:'CLOSE'});if(hadPanel){const target=returnFocus?.isConnected&&!returnFocus.closest('[hidden]')?returnFocus:document.querySelector(`#river-${state.river}`);target?.focus({preventScroll:true});}else document.querySelector('[data-home]').focus({preventScroll:true});}
function rememberFocus(trigger){if(!panel.contains(trigger)&&!preview.contains(trigger))returnFocus=trigger;else if(!returnFocus)returnFocus=document.querySelector(`#river-${state.river||'ability'}`);}
app.addEventListener('click',async e=>{
 const target=e.target.closest('button,a,[data-select-river]');if(!target||target.disabled)return;
 clearTimeout(hoverTimer);
 if(target.matches('[data-delete-local]')){const evidence=localEvidence(state.proof);if(!evidence||!window.confirm('确定移除这条证明吗？相关资本与河流关联也会一并移除。'))return;const storage=browserStorage(),workspace=readWorkspace(storage),record=workspace.data.growth.find(r=>growthEvidenceId(r.id)===evidence.id);let saved;
 if(record){saved=guardWorkspaceWrite(app,workspaceConnection.revokeProof(workspace.data,record.id));if(saved instanceof Promise)saved=await saved;}
 else{const capitalLinks=Object.values(explorationProfile.capitalLinks).filter(link=>link.evidence_id===evidence.id).map(link=>link.id),riverLinks=Object.values(explorationProfile.riverLinks).filter(link=>link.evidence_id===evidence.id).map(link=>link.id);saved=!evidence.id.startsWith('growth_')?explorationProfileConnection.commit(explorationProfile,{id:`change_delete_${evidence.id}`.slice(0,64),sessionId:'map-evidence-delete',scope:{evidence:[evidence.id],capitalLinks,riverLinks},operations:[]}):{ok:false};if(saved instanceof Promise)saved=await saved;}
 if(!saved.ok){announce('删除失败，原记录仍然保留。');return;}({profile:localProfile,explorationProfile,workspace:localWorkspace}=readLocalData());previewKey='';panelKey='';dispatch({type:'INFO',id:'local-proofs'});document.querySelector('#detail-title')?.focus({preventScroll:true});announce('证明及相关关联已删除。');return;}
 if(target.matches('[data-home]')){e.preventDefault();finishIntro();dispatch({type:'RESET'});return;}
 if(target.dataset.selectRiver){finishIntro();rememberFocus(target);const same=state.river===target.dataset.selectRiver&&!state.panel;dispatch(same?{type:'RESET'}:{type:'RIVER',id:target.dataset.selectRiver});announce(same?'河流摘要已收起。':`${riverById(target.dataset.selectRiver).name}摘要已展开。`);if(!same&&window.innerWidth<=760)preview.scrollIntoView({block:'nearest',behavior:media.matches?'instant':'smooth'});return;}
 if(target.dataset.proof){finishIntro();rememberFocus(target);dispatch({type:'PROOF',id:target.dataset.proof,river:target.dataset.river});document.querySelector('#detail-title')?.focus({preventScroll:true});if(window.innerWidth<=760)panel.scrollIntoView({block:'nearest',behavior:reduced()?'instant':'smooth'});return;}
 if(target.dataset.future){finishIntro();rememberFocus(target);const inReplacedContent=panel.contains(target)||preview.contains(target),same=state.panel==='future'&&state.river===target.dataset.future;dispatch({type:same?'CLOSE':'FUTURE',id:target.dataset.future});if(inReplacedContent&&!same)document.querySelector('#detail-title')?.focus({preventScroll:true});if(!same&&window.innerWidth<=760)panel.scrollIntoView({block:'nearest',behavior:media.matches?'instant':'smooth'});announce(same?'未来方向已收起。':'未来方向详情已打开，地图河流保持不变。');return;}
 if(target.dataset.direction){const wasTab=Boolean(target.closest('.direction-tabs'));dispatch({type:'DIRECTION',id:target.dataset.direction});if(wasTab)document.querySelector(`.direction-tabs [data-direction="${target.dataset.direction}"]`)?.focus({preventScroll:true});return;}
 if(target.dataset.panel){rememberFocus(target);dispatch({type:'INFO',id:target.dataset.panel});document.querySelector('#detail-title')?.focus({preventScroll:true});return;}
 if(target.matches('[data-close]'))return close();
 if(target.id==='motion-toggle'||target.matches('[data-toggle-motion]'))return toggleMotion();
 if(target.matches('[data-reduce]')){reduceByChoice=!reduceByChoice;applyReduced();document.querySelector('[data-reduce]')?.focus({preventScroll:true});announce(reduced()?'减少动态效果已开启。':'已恢复标准动态效果。');return;}
 if(target.id==='replay'||target.matches('[data-replay]')){dispatch({type:'RESET'});playIntro();return;}
 if(target.id==='skip-intro')finishIntro();
});
const hoverTarget=e=>e.target.closest('[data-hover-river]');
app.addEventListener('pointerover',e=>{if(e.pointerType==='touch')return;const el=hoverTarget(e);if(el){clearTimeout(hoverTimer);dispatch({type:'PREVIEW',id:el.dataset.hoverRiver});}if(preview.contains(e.target))clearTimeout(hoverTimer);});
app.addEventListener('pointerout',e=>{if(e.pointerType==='touch')return;if(hoverTarget(e)||preview.contains(e.target)){if(preview.contains(e.relatedTarget))return;hoverTimer=setTimeout(()=>dispatch({type:'PREVIEW',id:null}),300);}});
app.addEventListener('focusin',e=>{const el=hoverTarget(e);if(el)dispatch({type:'PREVIEW',id:el.dataset.hoverRiver});if(preview.contains(e.target))clearTimeout(hoverTimer);});
app.addEventListener('focusout',e=>{if(!preview.contains(e.relatedTarget)&&!e.relatedTarget?.closest('[data-hover-river]')){clearTimeout(hoverTimer);hoverTimer=setTimeout(()=>dispatch({type:'PREVIEW',id:null}),120);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&(state.panel||state.preview||state.river)){e.preventDefault();close();}});
document.querySelector('.coordinate-space').addEventListener('click',e=>{if(!e.target.closest('button,[data-select-river]')){if(state.panel)close();else dispatch({type:'RESET'});}});
function finishIntro(){clearTimeout(introTimer);shell.classList.remove('arriving');document.querySelector('#skip-intro').hidden=true;try{sessionStorage.setItem('moat-map-seen','1');}catch{/* Display-only preference; storage may be unavailable. */}}
function playIntro(){finishIntro();if(reduced()||paused){announce('已显示完整地图。动态暂停期间不播放显现。');return;}void shell.offsetWidth;shell.classList.add('arriving');document.querySelector('#skip-intro').hidden=false;introTimer=setTimeout(finishIntro,4800);}
function toggleMotion(){paused=!paused;if(paused)finishIntro();shell.classList.toggle('motion-paused',paused);const b=document.querySelector('#motion-toggle');b.innerHTML=icon(paused?'play':'pause');b.setAttribute('aria-label',paused?'恢复雾与地图动态':'暂停水流与雾动态');b.title=paused?'恢复动态':'暂停动态';sync();announce(paused?'环境动态已暂停，地图信息保持完整。':'环境动态已恢复。');}
function applyReduced(){shell.classList.toggle('reduced-motion',reduced());if(reduced())finishIntro();sync();}media.addEventListener('change',applyReduced);
document.addEventListener('visibilitychange',()=>shell.classList.toggle('page-hidden',document.hidden));
sync();applyReduced();let seen=false;try{seen=sessionStorage.getItem('moat-map-seen')==='1';}catch{}if(!seen)playIntro();

if(new URLSearchParams(location.search).get('panel')==='settings'){
 finishIntro();returnFocus=document.querySelector('.sidebar [data-panel="settings"]');
 dispatch({type:'INFO',id:'settings'});
 document.querySelector('#detail-title')?.focus({preventScroll:true});
 if(window.innerWidth<=760)panel.scrollIntoView({block:'nearest',behavior:'instant'});
}

if(new URLSearchParams(location.search).get('panel')==='local-proofs'){
 finishIntro();returnFocus=document.querySelector('#river-ability');
 dispatch({type:'INFO',id:'local-proofs'});
 document.querySelector('#detail-title')?.focus({preventScroll:true});
 if(window.innerWidth<=760)panel.scrollIntoView({block:'nearest',behavior:'instant'});
}
