import {reviewItems,confirmedContent} from './exploration-review.js';
import {initialExploration,explorationReduce,canContinue,steps} from './exploration-state.js';
import {buildPrototypeArtifacts,buildManualProposal,createExplorationSession,answersFromUi} from './exploration-domain.js';
import {createSyntheticAnalysisAdapter} from './exploration-analysis.js';
import {browserStorage,loadExplorationProfile,commitExplorationChange} from './exploration-storage.js';
import {escapeHtml} from './exploration-render-utils.js';
import {sidebarMarkup} from './sidebar.js';
const app=document.querySelector('#app');let state=structuredClone(initialExploration),profile=loadExplorationProfile(browserStorage()).profile,proposal=null,analysisController=null;
const analysisAdapter=createSyntheticAnalysisAdapter();
const explorationSession=createExplorationSession();
const sets={situation:[['continue','继续现在的方向'],['compare','比较几个方向'],['change','考虑转向'],['restart','重新开始'],['unclear','暂时说不清'],['other','其他']],blockers:[['basis','缺少判断依据'],['cost','担心转换成本'],['assets','看不清已有积累'],['proof','缺少可展示成果'],['reality','现实条件需要先照顾'],['interest','还没找到愿意投入的方向']],experience:[['course','课程 / 研究'],['work','工作任务'],['project','项目 / 作品'],['collaboration','协作经历'],['interest','长期兴趣实践'],['other','其他']],actions:[['organize','整理信息或需求'],['create','制作具体成果'],['coordinate','协调分工'],['solve','解决具体问题'],['research','研究与分析'],['practice','持续练习']],outcomes:[['artifact','完成可查看成果'],['problem','解决一个具体问题'],['feedback','得到他人反馈'],['continued','持续做了一段时间'],['unclear','暂时没有明确结果']],source:[['none','暂时没有来源'],['work','作品或项目记录'],['feedback','他人反馈'],['other','其他记录']]};
const label=(set,id)=>sets[set].find(x=>x[0]===id)?.[1]??id;
const choices=(field,set,multi=false,max=1)=>`<div class="explore-options">${sets[set].map(([id,name])=>{const on=multi?state.answers[field].includes(id):state.answers[field]===id;return `<button class="explore-option" data-${multi?'toggle':'single'}="${field}" data-value="${id}" data-max="${max}" aria-pressed="${on}"><span>${on?'✓':'○'}</span>${name}</button>`;}).join('')}</div>`;
const nav=(next='继续')=>`<div class="explore-nav"><button class="quiet-button" data-back>返回</button><button class="primary-button" data-next ${canContinue(state)?'':'disabled'}>${next}　→</button></div>`;
const textarea=(field,placeholder)=>`<textarea data-text="${field}" rows="3" placeholder="${escapeHtml(placeholder)}">${escapeHtml(state.answers[field])}</textarea>`;
function confirmationCard(item){const {id,title,body,detail,source,basis,rule,limit}=item,status=state.cards[id],deleted=status==='deleted',editing=status==='editing',shown=escapeHtml(state.edits[id]||body);return `<article class="understanding-card ${deleted?'is-deleted':''}" data-understanding-card="${id}" tabindex="-1"><p class="card-kicker">${escapeHtml(item.title)}</p><h2>${escapeHtml(detail||title)}</h2><p>${shown}</p><dl><dt>依据</dt><dd>${escapeHtml(basis)}</dd><dt>整理方式</dt><dd>${escapeHtml(rule)}</dd><dt>来自</dt><dd>${escapeHtml(source)}</dd><dt>仍需补充</dt><dd>${escapeHtml(limit)}</dd></dl>${editing?`<label>调整这条理解<textarea data-edit-value="${id}" rows="3">${shown}</textarea></label><button data-save-edit="${id}" class="small-action">保存修改</button>`:`<div class="card-actions">${deleted?`<button data-card="${id}" data-card-value="pending">撤销删除</button>`:`<button data-card="${id}" data-card-value="confirmed">${status==='confirmed'?'✓ 已保留':'保留'}</button><button data-card="${id}" data-card-value="editing">修改</button><button data-card="${id}" data-card-value="deleted">删除</button>`}</div>`}</article>`;}
function sidebar(){return sidebarMarkup('explore');}
function content(){const a=state.answers,artifacts=proposal&&['review','result','evidence','unknowns','preview','done'].includes(state.step)?buildPrototypeArtifacts(state,proposal):null,confirmed=artifacts?.confirmed??{evidence:[],capitalLinks:[],riverLinks:[],unknowns:[]},manualMode=Boolean(proposal&&!proposal.claims.length&&!proposal.capital_links.length&&!proposal.river_links.length&&!proposal.future_direction_drafts.length),associationNames=[...confirmed.capitalLinks.map(x=>({human:'人力资本',social:'社会资本',psychological:'心理资本',financial:'财务资本',physical:'身体资本'}[x.capital])),...confirmed.riverLinks.map(x=>({survival:'生存之河',ability:'能力之河',love:'热爱之河'}[x.river]))].join('、')||'本轮未保留关联',unknownSummary=escapeHtml(confirmed.unknowns.map(x=>x.explanation).join('；')||'本轮未保留未知说明');if(['result','evidence','unknowns'].includes(state.step))return confirmedContent(state.step,confirmed)+nav({result:'继续看依据',evidence:'看看未知',unknowns:'预览地图变化'}[state.step]);switch(state.step){
case'intro':return `<span class="explore-kicker">阶段 10 · 可点击内容原型</span><h1 tabindex="-1">从一段真实经历开始</h1><p class="lead">不用先把人生想明白。我们先了解你正在面对的选择，以及最近做过的一件事。</p><ul class="promise-list"><li>看到接近自己的选项，点它就好</li><li>可以返回修改，也可以跳过非必要问题</li><li>整理完成后，由你选择是否保存到当前浏览器</li></ul><div class="explore-nav"><a class="quiet-button" href="/">返回我的河</a><button class="primary-button" data-next>开始探索　→</button></div>`;
case'situation':return `<h1 tabindex="-1">这次你最想理清什么？</h1><p class="question-help">选择最接近的一项。它只帮助我们理解问题，不定义你的状态。</p>${choices('situation','situation')}${a.situation==='other'?textarea('situationOther','用自己的话简单写写'):''}${nav()}`;
case'blockers':return `<h1 tabindex="-1">现在最影响你做决定的是什么？</h1><p class="question-help">最多选 2 项，也可以先跳过。</p>${choices('blockers','blockers',true,2)}<p class="selection-count">已选 ${a.blockers.length} / 2</p>${nav(a.blockers.length?'继续':'暂时跳过')}`;
case'experience':return `<h1 tabindex="-1">最近哪段经历最能说明你做过什么？</h1><p class="question-help">先选一种经历，下一步再说你做了什么。</p>${choices('experience','experience')}${nav()}`;
case'actions':return `<h1 tabindex="-1">在这件事里，你具体做了什么？</h1><p class="question-help">最多选 3 项，可以补充自己的表达。</p>${choices('actions','actions',true,3)}${textarea('actionOther','还有什么具体行动？（可不填）')}<p class="selection-count">已选 ${a.actions.length} / 3</p>${nav()}`;
case'outcome':return `<h1 tabindex="-1">最后形成了什么？</h1><p class="question-help">结果不需要很大；暂时没有明确结果也可以继续。</p>${choices('outcomes','outcomes',true,3)}<fieldset><legend>有没有帮助回看的来源？（可选）</legend>${choices('source','source')}</fieldset><div class="explore-nav"><button class="quiet-button" data-back>返回</button><button class="primary-button" data-analyze ${canContinue(state)?'':'disabled'}>整理这段经历　→</button></div>`;
case'analyzing':return state.analysisStatus==='error'?`<span class="explore-kicker">理解整理暂时中断</span><h1 tabindex="-1">刚才没有整理完成</h1><p class="lead small">你的回答仍然保留，可以稍后重试，也可以只整理自己明确写下的内容。</p><div class="analysis-status is-error" role="alert"><strong>未生成任何理解或地图变化</strong><p>${state.analysisError||'本地演示分析暂时不可用。'}</p></div><div class="explore-nav"><button class="quiet-button" data-cancel-analysis>返回检查</button><button class="quiet-button" data-manual-analysis>手工整理</button><button class="primary-button" data-retry-analysis>重新整理</button></div>`:`<span class="explore-kicker">正在整理这段经历</span><h1 tabindex="-1">先把事实和推断分开</h1><p class="lead small">我们正在核对回答引用和结构，完成后仍由你逐条确认。</p><div class="analysis-status" role="status"><span class="analysis-pulse" aria-hidden="true"></span><strong>正在形成理解草稿…</strong><p>当前输入只用于本次页面演示，不会长期保存。</p></div><div class="explore-nav"><button class="quiet-button" data-cancel-analysis>取消并返回</button></div>`;
case'review':return `<span class="explore-kicker">理解确认 · ${manualMode?'手工整理':'本地规则整理'}</span><h1 tabindex="-1">看看有没有理解偏</h1><p class="lead small">${manualMode?'这里只保留你明确写下的经历、行动和结果；资本、河流与方向需要你以后自行补充。':'每条都可以保留、修改或删除；处理完全部内容后继续。'}</p><div class="understanding-list">${reviewItems(proposal).map(confirmationCard).join('')}</div>${nav('查看探索结果')}`;
case'preview':return `<span class="explore-kicker">探索结果 · 4 / 4${manualMode?' · 手工模式':''}</span><h1 tabindex="-1">保存前，看看会留下什么</h1><p class="lead small">${manualMode?'这次只保留你明确写下的内容，资本、河流与方向仍保持未知。':'只有选择“保存到我的河”，以下确认内容才会写入这个浏览器。'}</p><div class="map-update-preview"><div class="preview-copy"><strong>证明节点 · ${confirmed.evidence.length} 个</strong><p>${label('experience',a.experience)} · 用户自述</p><strong>定性关联 · ${confirmed.capitalLinks.length+confirmed.riverLinks.length} 条</strong><p>${associationNames}</p><strong>候选方向 · ${confirmed.directions?.length??0} 条</strong><p>保存候选后仍需另行核对，才会建立长期路径。</p><strong>继续保持未知 · ${confirmed.unknowns.length} 处</strong><p>${unknownSummary}</p></div></div>${manualMode?'<p class="question-help"><a class="text-button" href="/?view=paths">如果你已经有想探索的方向，可以自主建立路径</a>；它不会被当作规则或 AI 推荐。</p>':''}${state.updateStatus==='failed'?'<div class="save-error" role="alert"><strong>刚才没有保存成功</strong><p>你的回答和确认内容仍在。若其他页面已修改这次记录，请先核对，避免覆盖。也可以仅在本次查看。</p></div>':''}<p class="question-help">保存在当前浏览器，可稍后从「我的河」查看并删除；不会同步到账号或云端。</p><div class="explore-nav"><button class="quiet-button" data-back>返回查看</button><button class="quiet-button" data-skip-update>仅本次使用</button><button class="primary-button" data-apply-update>${state.updateStatus==='failed'?'重新保存':'保存到我的河'}</button></div>`;
case'done':return `<span class="explore-kicker">本次探索完成</span><h1 tabindex="-1">${state.updateStatus==='applied'?'已保存到这个浏览器':'这次没有保存到我的河'}</h1><p class="lead">${state.updateStatus==='applied'?'返回地图后，可以查看或删除刚刚确认的证明。':'确认内容只保留在当前页面，刷新或离开后不会继续保留。'}</p><div class="done-summary"><strong>${Object.values(state.cards).filter(x=>['confirmed','modified'].includes(x)).length} 条已保留或修改</strong><span>${state.updateStatus==='applied'?'已加入我的河':'仅本次使用'}</span></div><div class="explore-nav"><button class="quiet-button" data-back>返回预览</button><a class="primary-button" href="${state.updateStatus==='applied'?'/?panel=local-proofs':'/'}">返回我的河</a></div>`;}}
function render({cardId=null,top=null,focusSelector=null}={}){const i=steps.indexOf(state.step);app.innerHTML=`<main class="explore-shell">${sidebar()}<div class="explore-main"><header class="explore-header"><span>三河探索</span><span>探索原型 · 自主选择保存</span></header><section class="explore-card">${i>0&&i<6?`<div class="explore-progress"><span style="width:${i/5*100}%"></span></div><p class="progress-text">了解中 · ${i} / 5　进度表示步骤，不代表评分</p>`:''}${content()}<p id="explore-notice" class="sr-only" role="status"></p></section></div></main>`;if(cardId){const card=document.querySelector(`[data-understanding-card="${cardId}"]`);if(card&&top!==null)window.scrollBy(0,card.getBoundingClientRect().top-top);(focusSelector?card?.querySelector(focusSelector):card)?.focus({preventScroll:true});}else document.querySelector('h1')?.focus();}
async function startAnalysis(){
 analysisController?.abort();const controller=new AbortController();analysisController=controller;proposal=null;state=explorationReduce(state,{type:'ANALYSIS_START'});render();
 const session=explorationSession;session.answers=answersFromUi(state);
 try{proposal=await analysisAdapter.analyze(session,{signal:controller.signal});state=explorationReduce(state,{type:'ANALYSIS_SUCCESS',cardIds:reviewItems(proposal).map(x=>x.id)});render();}
 catch(error){if(error.name==='AbortError')return;state=explorationReduce(state,{type:'ANALYSIS_FAIL',error:'本地演示分析暂时不可用，请重试。'});render();}
 finally{if(analysisController===controller)analysisController=null;}
}
app.addEventListener('click',event=>{const t=event.target.closest('button');if(!t)return;const cardId=t.dataset.card||t.dataset.saveEdit;if(cardId){const top=t.closest('[data-understanding-card]').getBoundingClientRect().top;if(t.dataset.saveEdit){const value=document.querySelector(`[data-edit-value="${cardId}"]`).value.trim();if(!value)return;const changed=Object.values(proposal??{}).flatMap(value=>Array.isArray(value)?value:[]).find(item=>item.id===cardId);const dependentIds=changed?.id?[...new Set(Object.values(proposal??{}).flatMap(value=>Array.isArray(value)?value:[]).filter(item=>item.evidence_id===changed.id).map(item=>item.id))]:[];state=explorationReduce(state,{type:'EDIT',id:cardId,value,dependentIds});render({cardId,top});return;}state=explorationReduce(state,{type:'CARD',id:cardId,value:t.dataset.cardValue});const focusSelector=t.dataset.cardValue==='editing'?`[data-edit-value="${cardId}"]`:`[data-card="${cardId}"]`;render({cardId,top,focusSelector});return;}if(t.hasAttribute('data-analyze')||t.hasAttribute('data-retry-analysis')){startAnalysis();return;}if(t.hasAttribute('data-manual-analysis')){analysisController?.abort();analysisController=null;proposal=buildManualProposal({...explorationSession,answers:answersFromUi(state)});state=explorationReduce(state,{type:'ANALYSIS_SUCCESS',cardIds:reviewItems(proposal).map(x=>x.id)});render();return;}if(t.hasAttribute('data-cancel-analysis')){analysisController?.abort();analysisController=null;state=explorationReduce(state,{type:'ANALYSIS_CANCEL'});}else if(t.hasAttribute('data-next'))state=explorationReduce(state,{type:'NEXT'});else if(t.hasAttribute('data-back'))state=explorationReduce(state,{type:'BACK'});else if(t.hasAttribute('data-apply-update')){const saved=commitExplorationChange(browserStorage(),profile,buildPrototypeArtifacts(state,proposal).changeSet);if(!saved.ok)state=explorationReduce(state,{type:'APPLY_FAIL'});else{profile=saved.profile;state=explorationReduce(state,{type:'APPLY_UPDATE'});}}else if(t.hasAttribute('data-skip-update'))state=explorationReduce(state,{type:'SKIP_UPDATE'});else if(t.dataset.single)state=explorationReduce(state,{type:'SINGLE',field:t.dataset.single,value:t.dataset.value});else if(t.dataset.toggle){const old=state;state=explorationReduce(state,{type:'TOGGLE',field:t.dataset.toggle,value:t.dataset.value,max:Number(t.dataset.max)});if(old===state){document.querySelector('#explore-notice').textContent=`最多选择 ${t.dataset.max} 项`;return;}}else return;render();});
app.addEventListener('input',event=>{if(event.target.dataset.text){state=explorationReduce(state,{type:'TEXT',field:event.target.dataset.text,value:event.target.value});document.querySelector('[data-next]').disabled=!canContinue(state);}});render();
