import {createGrowthProof} from './growth-proof.js';
import {browserStorage} from './exploration-storage.js';
import {growthContext,capitalNames,riverNames,saveWorkspaceItem,growthTypes,newGrowth,readWorkspace,commitWorkspace,upsertItem,deleteItem,validDate} from './workspace-model.js';
import {showFormError} from './workspace-form.js';
import {workspaceConnection,readActiveWorkspace as readWorkspace,activeWorkspaceLabel} from './workspace-connection.js';
import {workspaceSourceMarkup,guardWorkspaceWrite} from './workspace-feedback.js';
import {sidebarMarkup} from './sidebar.js';

const app=document.querySelector('#app');
const loaded=readWorkspace(browserStorage());
let data=loaded.data,draft=null,dirty=false,selected=null,filter='all',group='time',proofDraft=null,notice=loaded.ok?'':loaded.error;
const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes=[['/','我的河'],['/?view=explore','探索'],['/?view=paths','未来路径'],['/?view=plans','护城河计划'],['/?view=growth','成长记录']];
const sorted=()=>[...data.growth].filter(r=>filter==='all'||r.type===filter).sort((a,b)=>b.date.localeCompare(a.date));
const context=r=>growthContext(data,r);
function groupedRecords(){const records=sorted();if(group==='time')return [['按时间',records]];const map=new Map();for(const r of records){const contexts=context(r);for(const c of contexts.length?contexts:[{}]){const key=group==='river'?(c.river??'none'):(c.pathId||'none'),name=group==='river'?(riverNames[c.river]??'未关联河流'):(c.pathName||'未关联路径');if(!map.has(key))map.set(key,{name,records:[]});if(!map.get(key).records.some(x=>x.id===r.id))map.get(key).records.push(r);}}return [...map.values()].map(x=>[x.name,x.records]);}
const button=(text,attrs='',primary=false)=>`<button type="button" class="${primary?'primary-button':'quiet-button'}" ${attrs}>${text}</button>`;
function field(label,name,value,{short=false,required=false}={}){return `<label class="workspace-field"><span>${label}${required?' · 必填':''}</span>${short?`<input name="${name}" value="${e(value)}" maxlength="120" ${required?'required':''}>`:`<textarea name="${name}" rows="3" maxlength="4000">${e(value)}</textarea>`}</label>`;}
function sidebar(){return sidebarMarkup('growth');}
function timeline(){return `<aside class="workspace-list growth-timeline" aria-label="成长记录"><div class="workspace-list-head"><span>走过的足迹</span>${button('＋ 记录','data-new')}</div><div class="growth-group-tabs" role="group" aria-label="记录分组">${[['time','按时间'],['river','按河流'],['path','按路径']].map(([id,name])=>`<button data-group="${id}" aria-pressed="${group===id}">${name}</button>`).join('')}</div><label class="workspace-field growth-filter"><span class="sr-only">筛选记录类型</span><select data-filter>${Object.entries({all:'全部记录',...growthTypes}).map(([id,name])=>`<option value="${id}" ${filter===id?'selected':''}>${name}</option>`).join('')}</select></label>${groupedRecords().map(([name,records])=>`<section class="growth-record-group"><h3>${e(name)}</h3>${records.map(r=>`<button type="button" class="workspace-item growth-timeline-item ${selected===r.id?'selected':''}" data-select="${e(r.id)}"><time datetime="${r.date}">${r.date.replaceAll('-',' / ')}</time><small>${growthTypes[r.type]}</small><strong>${e(r.name)}</strong></button>`).join('')}</section>`).join('')||'<p class="workspace-list-empty">这里还没有记录。每一小步都可以留下。</p>'}</aside>`;}
function empty(){return `<div class="workspace-empty"><span class="explore-kicker">日常有回声，积累有来处</span><h2 tabindex="-1">有些变化，值得记下来</h2><p>做完一件小事、收到一次反馈，或发现一种更适合自己的做法。给它留几句话，之后就能回看自己怎样走到这里。</p>${button('记下今天的一小步','data-new',true)}<p class="workspace-footnote">由你记录，保存在当前浏览器。</p></div>`;}
function note(label,value){return value?`<section class="workspace-note"><h3>${label}</h3><p>${e(value)}</p></section>`:'';}
function proofEditor(r){return `<form id="proof-form"><h2 tabindex="-1">确认保存为证明</h2>${note('具体行动',r.action)}${note('成果与来源',[r.result,r.source].filter(Boolean).join('；'))}<label class="workspace-field"><span>支持的资本 · 可不选</span><select name="capital"><option value="">暂不关联</option>${Object.entries(capitalNames).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select></label><label class="workspace-field"><span>支持的河流 · 可不选</span><select name="river"><option value="">暂不关联</option>${Object.entries(riverNames).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select></label>${field('为什么支持这些关联','explanation','')}<p>保存这份已确认的成果快照到我的河。之后修改原记录，需要再次确认才能更新证明；撤回证明保留原记录。</p><p data-form-error role="alert" tabindex="-1" hidden></p><button class="primary-button" type="submit">确认保存到我的河</button>${button('取消','data-cancel-proof')}</form>`;}
function detail(r){const plan=data.plans.find(p=>p.id===r.planId),milestone=plan?.milestones.find(m=>m.id===r.milestoneId);return `<article class="workspace-detail"><div class="workspace-detail-top"><span class="explore-kicker">${r.date} · ${growthTypes[r.type]}</span>${button('编辑','data-edit')}</div><h2 tabindex="-1">${e(r.name)}</h2>${note('我做了什么',r.action)}${note('形成了什么',r.result)}${note('发现与复盘',r.reflection)}${note('回看的来源',r.source)}${plan||r.planName?`<section class="workspace-note"><h3>这一步从哪里来</h3>${plan?`<a class="text-button" href="/?view=plans&item=${encodeURIComponent(plan.id)}">${e(plan.name)} →</a>`:`<p>${e(r.planName)} · 原计划已移除或解除关联</p>`}${milestone?`<p>里程碑：${e(milestone.name)}</p>`:r.milestoneName?`<p>原里程碑：${e(r.milestoneName)} · 已移除或解除关联</p>`:''}</section>`:''}<p class="workspace-footnote">${r.proof?'已保存一份确认时的成果快照到我的河。修改原记录后，请重新确认以更新证明。':'这条记录尚未保存为地图证明；勾选完成不会增加资本。'}</p><div class="workspace-actions">${button(r.proof?'重新确认并更新证明':'保存为证明','data-publish')}${r.proof?`<a class="text-button" href="/?panel=local-proofs">到我的河查看 →</a>${button('撤回地图证明','data-revoke')}`:''}</div><div class="workspace-actions">${button('删除记录','data-delete')}</div></article>`;}
function planOptions(){return '<option value="">独立记录，暂不关联</option>'+data.plans.map(p=>`<option value="${e(p.id)}" ${draft.planId===p.id?'selected':''}>${e(p.name)}</option>`).join('');}
function milestoneOptions(){const plan=data.plans.find(p=>p.id===draft.planId);return '<option value="">暂不关联里程碑</option>'+(plan?.milestones??[]).map(m=>`<option value="${e(m.id)}" ${draft.milestoneId===m.id?'selected':''}>${e(m.name)}</option>`).join('');}
function editor(){return `<form id="growth-form" novalidate><span class="explore-kicker">留下一段自己的记录</span><h2 tabindex="-1">${data.growth.some(r=>r.id===draft.id)?'再补充一点细节':'今天，向前走了哪一步？'}</h2>${field('标题','name',draft.name,{short:true,required:true})}<div class="workspace-form-grid"><label class="workspace-field"><span>发生日期 · 必填</span><input type="date" name="date" value="${e(draft.date)}" required></label><label class="workspace-field"><span>记录类型</span><select name="type">${Object.entries(growthTypes).map(([id,name])=>`<option value="${id}" ${draft.type===id?'selected':''}>${name}</option>`).join('')}</select></label></div>${field('我做了什么','action',draft.action)}${field('形成了什么 · 成果或反馈','result',draft.result)}${field('发现与复盘 · 下次想怎样做','reflection',draft.reflection)}${field('回看的来源 · 可选的作品、笔记或链接','source',draft.source)}<div class="workspace-form-grid"><label class="workspace-field"><span>关联计划 · 可选</span><select name="planId">${planOptions()}</select></label><label class="workspace-field"><span>关联里程碑 · 可选</span><select name="milestoneId" ${draft.planId?'':'disabled'}>${milestoneOptions()}</select></label></div><p class="workspace-footnote">保存后可以继续编辑或删除。原有计划的完成状态保持原样。</p><p data-form-error class="workspace-form-error" role="alert" tabindex="-1" hidden></p><div class="workspace-actions"><button class="primary-button" type="submit">保存记录</button>${button('取消','data-cancel')}</div></form>`;}
function render(focus=true){const record=data.growth.find(r=>r.id===selected);app.innerHTML=`<main class="explore-shell workspace-shell">${sidebar()}<div class="explore-main"><header class="workspace-header"><div><span class="explore-kicker">人生三河 · 成长记录原型</span><h1>成长记录</h1><p>每一个向前的小步，都有迹可循。</p></div><a class="quiet-button" href="/?view=plans">回到护城河计划 →</a></header><nav class="workspace-mobile-nav" aria-label="工作区导航">${routes.map(([href,name])=>`<a href="${href}">${name}</a>`).join('')}</nav>${workspaceSourceMarkup()}<p id="growth-notice" class="workspace-notice" role="status">${e(notice)}</p><div class="workspace-layout">${timeline()}<section class="workspace-paper">${proofDraft?proofEditor(proofDraft):draft?editor():record?detail(record):empty()}</section></div></div></main>`;if(proofDraft?.selection)for(const [key,value] of Object.entries(proofDraft.selection)){const el=document.querySelector(`#proof-form [name="${key}"]`);if(el)el.value=value;}if(focus)document.querySelector('.workspace-paper h2')?.focus({preventScroll:true});}
function capture(){const f=new FormData(document.querySelector('#growth-form'));for(const key of ['name','date','type','action','result','reflection','source','planId','milestoneId'])draft[key]=String(f.get(key)??'');}
function leave(){return !dirty||window.confirm('有尚未保存的记录，确定放弃修改吗？');}
function persist(result){const finish=result=>{if(!result.ok){if(draft)showFormError(document.querySelector('#growth-form'),result.error);else{const node=document.querySelector('#growth-notice');node.textContent=result.error;node.setAttribute('role','alert');node.classList.add('is-error');}return false;}data=result.data;return true;};const guarded=guardWorkspaceWrite(app,result);return guarded instanceof Promise?guarded.then(finish):finish(guarded);}
app.addEventListener('input',event=>{if(event.target.closest('#proof-form')){dirty=true;proofDraft.selection=Object.fromEntries(new FormData(document.querySelector('#proof-form')));}if(event.target.closest('#growth-form')){dirty=true;if(!['planId','milestoneId'].includes(event.target.name))capture();event.target.removeAttribute('aria-invalid');}});
app.addEventListener('change',event=>{const t=event.target;if(t.hasAttribute('data-filter')){if(!leave()){t.value=filter;return;}proofDraft=null;draft=null;dirty=false;filter=t.value;selected=sorted()[0]?.id??null;render(false);return;}if(t.name==='planId'){const old=draft.planId;capture();if(old!==draft.planId){draft.milestoneId='';draft.planName='';draft.milestoneName='';}const select=document.querySelector('[name=milestoneId]');select.innerHTML=milestoneOptions();select.disabled=!draft.planId;dirty=true;}});
app.addEventListener('submit',async event=>{if(event.target.id==='proof-form'){event.preventDefault();const f=new FormData(event.target);try{let saved=guardWorkspaceWrite(app,workspaceConnection.confirmProof(data,proofDraft.id,Object.fromEntries(f)));if(saved instanceof Promise)saved=await saved;if(!saved.ok)throw new Error(saved.error);data=saved.data;proofDraft=null;dirty=false;notice='证明已保存到我的河；河道宽度与完成状态保持原样。';render();}catch(error){showFormError(event.target,error.message);}return;}if(event.target.id!=='growth-form')return;event.preventDefault();capture();draft.name=draft.name.trim();let problem=null;if(!draft.name)problem={message:'请给这条记录写一个标题。',field:'name'};else if(!validDate(draft.date))problem={message:'请填写有效的发生日期。',field:'date'};else if(![draft.action,draft.result,draft.reflection].some(s=>s.trim()))problem={message:'写下一点行动、成果或复盘内容，再保存记录。',field:'action'};if(problem){showFormError(event.target,problem.message,problem.field);return;}if(!event.target.checkValidity()){event.target.reportValidity();return;}const plan=data.plans.find(p=>p.id===draft.planId),milestone=plan?.milestones.find(m=>m.id===draft.milestoneId);if(plan)draft.planName=plan.name;if(milestone)draft.milestoneName=milestone.name;let saved=guardWorkspaceWrite(app,workspaceConnection.saveItem(data,'growth',draft));if(saved instanceof Promise)saved=await saved;if(!saved.ok){showFormError(event.target,saved.error);return;}data=saved.data;selected=draft.id;filter='all';draft=null;dirty=false;notice='这一步已经记下，保存在'+activeWorkspaceLabel()+'。';render();});
app.addEventListener('click',async event=>{const t=event.target.closest('button,a');if(!t)return;if(t.tagName==='A'){if(!leave())event.preventDefault();else dirty=false;return;}if(t.hasAttribute('data-publish')){proofDraft=structuredClone(data.growth.find(r=>r.id===selected));dirty=true;render();return;}if(t.hasAttribute('data-cancel-proof')){proofDraft=null;dirty=false;render();return;}if(t.hasAttribute('data-revoke')){if(!window.confirm('撤回地图证明及其关联？原成长记录会保留。'))return;let saved=guardWorkspaceWrite(app,workspaceConnection.revokeProof(data,selected));if(saved instanceof Promise)saved=await saved;if(!saved.ok){notice=saved.error;}else{data=saved.data;notice='地图证明已撤回，原记录仍保留。';}render();return;}if(t.hasAttribute('data-new')){if(!leave())return;proofDraft=null;draft=newGrowth();dirty=false;render();return;}if(t.dataset.select){if(!leave())return;proofDraft=null;selected=t.dataset.select;draft=null;dirty=false;render();return;}if(t.hasAttribute('data-edit')){draft=structuredClone(data.growth.find(r=>r.id===selected));dirty=false;render();return;}if(t.hasAttribute('data-cancel')){if(!leave())return;draft=null;dirty=false;render();return;}if(t.hasAttribute('data-delete')){if(!window.confirm('删除这条成长记录及其已保存的地图证明和关联？计划和里程碑会保留，此操作无法撤销。'))return;const saving=persist(workspaceConnection.deleteRecord(data,'growth',selected));if(saving instanceof Promise?await saving:saving){selected=sorted()[0]?.id??null;notice='记录已删除，关联计划保持原样。';render();}}});
app.addEventListener('click',event=>{const t=event.target.closest('[data-group]');if(!t)return;if(draft)capture();if(proofDraft)proofDraft.selection=Object.fromEntries(new FormData(document.querySelector('#proof-form')));group=t.dataset.group;render(false);});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
const params=new URLSearchParams(location.search),plan=data.plans.find(p=>p.id===params.get('plan'));
selected=data.growth.find(r=>r.id===params.get('item'))?.id??sorted()[0]?.id??null;
if(plan){draft=newGrowth();draft.planId=plan.id;draft.planName=plan.name;const m=plan.milestones.find(m=>m.id===params.get('milestone'));if(m){draft.milestoneId=m.id;draft.milestoneName=m.name;}dirty=true;}
render();
