import {prepareDirectionPath} from './direction-path.js';
import {validateWorkspaceDraft,showFormError} from './workspace-form.js';
import {browserStorage} from './exploration-storage.js';
import {explorationProfileConnection} from './exploration-connection.js';
import {riverNames,capitalNames,statusNames,newId,newPath,newPlan,newMilestone,planPlacement} from './workspace-model.js';
import {workspaceConnection,readActiveWorkspace as readWorkspace} from './workspace-connection.js';
import {workspaceSourceMarkup,guardWorkspaceWrite} from './workspace-feedback.js';
import {sidebarMarkup} from './sidebar.js';

const app=document.querySelector('#app'),params=new URLSearchParams(location.search),kind=params.get('view')==='plans'?'plans':'paths',isPlan=kind==='plans',title=isPlan?'护城河计划':'未来路径';
const loaded=readWorkspace(browserStorage());let data=loaded.data,selected=data[kind][0]?.id??null,draft=null,dirty=false,milestoneOnly=null,comparing=false,overview=!params.has('item')&&!params.has('path')&&!params.has('direction'),overviewSelection=false,compareIds=[],notice=loaded.ok?'':loaded.error,error=!loaded.ok;
const initialRiver=params.get('river')&&riverNames[params.get('river')]?params.get('river'):(data.paths.find(p=>p.id===params.get('path'))?.river??data[kind][0]?.river??'ability'),openRivers=new Set([initialRiver]),openPaths=new Set(params.get('path')?[params.get('path')]:[]);
if(isPlan&&selected){const plan=data.plans.find(item=>item.id===selected);for(const pathId of plan?.pathIds??[]){openPaths.add(pathId);const path=data.paths.find(item=>item.id===pathId);if(path)openRivers.add(path.river);}}
if(overview){for(const river of Object.keys(riverNames))openRivers.add(river);if(isPlan)for(const path of data.paths)openPaths.add(path.id);}
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),button=(label,attrs='',primary=false)=>`<button type="button" class="${primary?'primary-button':'quiet-button'}" ${attrs}>${label}</button>`;
const routes=[['/','我的河'],['/?view=explore','探索'],['/?view=paths','未来路径'],['/?view=plans','护城河计划'],['/?view=growth','成长记录']];
function sidebar(){return sidebarMarkup(kind);}
function field(label,name,value,{short=false,required=false}={}){return `<label class="workspace-field"><span>${label}${required?' · 必填':''}</span>${short?`<input name="${name}" value="${e(value)}" maxlength="120" ${required?'required':''}>`:`<textarea name="${name}" rows="3" maxlength="4000">${e(value)}</textarea>`}</label>`;}
function select(label,name,values,value){return `<label class="workspace-field"><span>${label}</span><select name="${name}">${Object.entries(values).map(([id,text])=>`<option value="${id}" ${id===value?'selected':''}>${text}</option>`).join('')}</select></label>`;}
const section=(label,value)=>`<section class="workspace-note"><h3>${label}</h3><p>${e(value||'还可以慢慢补充。')}</p></section>`,plansFor=path=>data.plans.filter(plan=>plan.pathIds.includes(path.id)&&planPlacement(data,plan).ok);
function pathNode(path,nested=false){const open=openPaths.has(path.id),plans=plansFor(path),showSelection=!overview||overviewSelection;return `<div class="river-axis-branch ${nested?'has-plans':''}"><span class="axis-connector" aria-hidden="true"></span><button class="workspace-axis-node path-axis-node ${showSelection&&selected===path.id&&!isPlan?'selected':''}" data-${nested?'toggle-path':'select'}="${e(path.id)}" aria-expanded="${nested?open:false}"><span class="axis-dot"></span><span><small>${overview?'未来路径 · ':''}${statusNames[path.status]}</small><strong>${e(path.name)}</strong></span>${nested?`<i>${plans.length} 个计划</i>`:''}</button>${!nested?`<label class="workspace-compare-choice"><input type="checkbox" data-compare="${e(path.id)}" ${compareIds.includes(path.id)?'checked':''}>加入比较</label>`:''}${nested&&open?`<div class="plan-axis-children">${plans.map(plan=>`<button class="workspace-axis-node plan-axis-node ${showSelection&&selected===plan.id?'selected':''}" data-select="${e(plan.id)}"><span class="axis-dot"></span><span><small>${overview?'护城河计划 · ':''}${statusNames[plan.status]}</small><strong>${e(plan.name)}</strong></span></button>`).join('')}${button('＋ 新建计划',`data-new-plan="${e(path.id)}"`)}</div>`:''}</div>`;}
function riverAxis(){const unresolved=isPlan?data.plans.filter(plan=>!planPlacement(data,plan).ok):[],showSelection=!overview||overviewSelection;return `<aside class="workspace-list river-axis" aria-label="${title}河流轴"><div class="workspace-list-head"><span>三条河 · ${data[kind].length} 条记录</span>${isPlan?button('＋ 新建计划','data-create-plan',true):''}</div>${Object.entries(riverNames).map(([river,name])=>{const paths=data.paths.filter(path=>path.river===river),open=openRivers.has(river);return `<section class="river-axis-group river-${river}"><button class="river-axis-head" data-river="${river}" aria-expanded="${open}"><span class="river-axis-mark"></span><span><strong>${name}</strong><small>${paths.length} 条未来路径</small></span><i>${open?'收起':'展开'}</i></button>${open?`<div class="river-axis-content">${paths.map(path=>pathNode(path,isPlan)).join('')||'<p class="workspace-list-empty">这条河下还没有未来路径。</p>'}${!isPlan?button('＋ 新建路径',`data-new-path="${river}"`,true):!paths.length?`<a class="quiet-button" href="/?view=paths&river=${river}&new=1">＋ 先新建路径</a>`:''}</div>`:''}</section>`;}).join('')}${isPlan&&unresolved.length?`<section class="river-axis-unresolved"><h3>待重新选择归属</h3>${unresolved.map(plan=>`<button class="workspace-axis-node plan-axis-node ${showSelection&&selected===plan.id?'selected':''}" data-select="${e(plan.id)}"><span class="axis-dot"></span><strong>${e(plan.name)}</strong></button>`).join('')}</section>`:''}${!isPlan?button(`比较所选路径（${compareIds.length}）`,'data-show-compare '+(compareIds.length<2?'disabled':'')):''}</aside>`;}
function empty(){return `<div class="workspace-empty"><span class="explore-kicker">${isPlan?'路径下面，长出计划':'从三条河，走向不同可能'}</span><h2 tabindex="-1">${isPlan?(data.paths.length?'先展开一条路径':'先为计划建立一条路径'):'先展开一条河流'}</h2><p>${isPlan?'每个计划都属于一条未来路径，并继承这条路径的河流。已有路径可直接新建计划；还没有路径时，从河流下方新建路径，保存后即可建立计划。':'未来路径按生存、能力与热爱三条河组织。选择一条河，再写下想验证的方向。'}</p></div>`;}
function detail(item){const placement=isPlan?planPlacement(data,item):null;return `<div class="workspace-detail"><div class="workspace-detail-top"><span class="workspace-river-meta"><strong>${riverNames[item.river]}</strong><i>· ${statusNames[item.status]}</i></span>${button('编辑','data-edit')}</div><h2 tabindex="-1">${e(item.name)}</h2>${isPlan&&!placement.ok?'<p class="workspace-placement-warning">这条旧计划需要重新选择一条未来路径，保存时河流会随路径更新。</p>':''}${section(isPlan?'想建设什么':'想走向哪里',item.goal)}${isPlan?planDetail(item):pathDetail(item)}${section('留给自己的备注',item.notes)}<div class="workspace-actions">${isPlan?button('＋ 添加里程碑','data-add-detail',true):`<a class="primary-button" href="/?view=plans&path=${encodeURIComponent(item.id)}">新建计划</a>`}${isPlan?`<a class="quiet-button" href="/?view=growth&plan=${encodeURIComponent(item.id)}">记录这次进展</a>`:''}${button('删除'+(isPlan?'计划':'路径'),'data-delete')}<button type="button" class="quiet-button workspace-overview-action" data-collapse-detail>收起详情</button></div></div>`;}
function pathDetail(item){return `<div class="workspace-note-grid">${section('已有支持',item.support)}${section('还缺什么',item.gap)}${section('现实条件',item.constraints)}${section('先验证的一小步',item.nextAction)}</div><section class="workspace-note"><h3>这条路径下的计划</h3>${plansFor(item).map(p=>`<a class="text-button" href="/?view=plans&item=${encodeURIComponent(p.id)}&path=${encodeURIComponent(item.id)}">${e(p.name)} →</a>`).join('')||'<p>还没有计划，可以从一个小目标开始。</p>'}</section>`;}
function planDetail(item){const paths=planPlacement(data,item).paths??[];return `${paths.length?`<section class="workspace-note"><h3>所属未来路径</h3>${paths.map(path=>`<a class="text-button" href="/?view=paths&item=${encodeURIComponent(path.id)}&river=${path.river}">${e(path.name)} →</a>`).join('')}</section>`:''}<section class="workspace-note"><h3>准备积累的资本</h3><div class="workspace-tags">${item.capitals.map(c=>`<span>${capitalNames[c]}</span>`).join('')}</div></section><section class="workspace-note milestone-axis"><h3>里程碑</h3><p class="workspace-footnote">完成只记录推进状态；成果经确认后才回到地图。</p>${item.milestones.map((m,index)=>`<article class="workspace-milestone"><span class="milestone-index">${index+1}</span><div class="workspace-detail-top"><h4>${e(m.name)}</h4><label><input type="checkbox" data-milestone-toggle="${e(m.id)}" ${m.done?'checked':''}> 已完成</label></div><p>完成标准：${e(m.criterion||'待补充')}</p>${button('编辑里程碑',`data-edit-milestone="${e(m.id)}"`)}<a class="text-button" href="/?view=growth&plan=${encodeURIComponent(item.id)}&milestone=${encodeURIComponent(m.id)}">记下这一步的进展 →</a>${m.actions.map(a=>`<label class="workspace-action-check"><input type="checkbox" data-action-toggle="${e(a.id)}" data-milestone="${e(m.id)}" ${a.done?'checked':''}><span>${e(a.text)}</span></label>`).join('')}</article>`).join('')||'<p>还没有里程碑。点击下方按钮建立第一个。</p>'}</section><section class="workspace-note"><h3>已关联的成长记录</h3>${data.growth.filter(r=>r.planId===item.id).map(r=>`<a class="text-button" href="/?view=growth&item=${encodeURIComponent(r.id)}">${e(r.name)} →</a>`).join('')||'<p>还没有关联记录。</p>'}</section>`;}
function milestoneEditor(m,index){return `<fieldset class="workspace-milestone" data-milestone-editor="${e(m.id)}"><legend>里程碑 ${index+1}</legend>${field('名称',`m-name-${m.id}`,m.name,{short:true,required:true})}${field('怎样算完成',`m-criterion-${m.id}`,m.criterion)}${field('具体行动（每行一项）',`m-actions-${m.id}`,m.actions.map(a=>a.text).join('\n'))}<div class="workspace-actions">${button('上移',`data-up="${e(m.id)}" ${index===0?'disabled':''}`)}${button('移除',`data-remove-milestone="${e(m.id)}"`)}</div></fieldset>`;}
function saveActions(label){return `<div class="workspace-actions"><button class="primary-button" type="submit">${label}</button>${button('取消','data-cancel')}<button class="quiet-button workspace-overview-action" type="submit" data-save-overview>保存并查看概览</button></div>`;}
function editor(){if(milestoneOnly){const m=draft.milestones.find(m=>m.id===milestoneOnly);return `<form id="workspace-form" novalidate><h2 tabindex="-1">编辑里程碑</h2>${milestoneEditor(m,draft.milestones.indexOf(m))}<p data-form-error class="workspace-form-error" role="alert" tabindex="-1" hidden></p>${saveActions('保存里程碑')}</form>`;}return `<form id="workspace-form" novalidate><span class="explore-kicker">${data[kind].some(i=>i.id===draft.id)?'调整':'新建'}${title}</span><h2 tabindex="-1">${isPlan?'沿着路径，把目标拆成小步':'让这个方向更清楚一些'}</h2>${field('名称','name',draft.name,{short:true,required:true})}<div class="workspace-form-grid">${isPlan?`${select('所属河流','river',riverNames,draft.river)}<label class="workspace-field"><span>所属未来路径 · 必填</span><select name="pathId"><option value="">请选择所属路径</option>${draft.pathIds.length>1&&planPlacement(data,draft).ok?'<option value="__keep__" selected>保留原有同河路径关联</option>':''}${data.paths.filter(p=>p.river===draft.river).map(p=>`<option value="${e(p.id)}" ${draft.pathIds.length===1&&draft.pathIds[0]===p.id?'selected':''}>${e(p.name)}</option>`).join('')}</select></label>`:select('所属河流','river',riverNames,draft.river)}${select('当前状态','status',statusNames,draft.status)}</div>${field(isPlan?'资本建设目标':'目标 · 为什么想走这条路','goal',draft.goal)}${isPlan?`<fieldset><legend>准备建设的资本 · 至少一项</legend><div class="workspace-checks">${Object.entries(capitalNames).map(([id,name])=>`<label><input type="checkbox" name="capitals" value="${id}" ${draft.capitals.includes(id)?'checked':''}>${name}</label>`).join('')}</div></fieldset><div>${draft.milestones.map(milestoneEditor).join('')}</div>${button('＋ 添加里程碑','data-add-milestone',true)}`:`<div class="workspace-form-grid">${field('已有支持','support',draft.support)}${field('还缺什么','gap',draft.gap)}${field('现实条件','constraints',draft.constraints)}${field('先验证的一小步','nextAction',draft.nextAction)}</div>`}${field('备注','notes',draft.notes)}<p data-form-error class="workspace-form-error" role="alert" tabindex="-1" hidden></p>${saveActions(`保存${isPlan?'计划':'路径'}`)}</form>`;}
function comparison(){const items=data.paths.filter(p=>compareIds.includes(p.id));return `<div class="workspace-detail"><h2 tabindex="-1">这几条路，各自意味着什么？</h2><div class="workspace-table-wrap"><table><thead><tr><th>观察角度</th>${items.map(p=>`<th>${e(p.name)}</th>`).join('')}</tr></thead><tbody>${[['goal','目标'],['support','已有支持'],['gap','待补与待验证'],['constraints','现实条件'],['nextAction','下一小步']].map(([key,name])=>`<tr><th>${name}</th>${items.map(p=>`<td>${e(p[key]||'待补充')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${button('返回详情','data-close-compare')}</div>`;}
function render(focus=true){const item=data[kind].find(x=>x.id===selected),activeRiver=comparing?'':(draft?.river??item?.river??'');app.innerHTML=`<main class="explore-shell workspace-shell">${sidebar()}<div class="explore-main"><header class="workspace-header"><div><span class="explore-kicker">人生三河 · 河流轴工作区</span><h1>${title}</h1><p>${isPlan?'从河流进入路径，再把路径拆成计划与里程碑。':'从三条河展开未来路径，保留多种可以验证的走法。'}</p></div><button type="button" class="workspace-view-toggle" data-overview aria-pressed="${overview}">概览</button></header><nav class="workspace-mobile-nav">${routes.map(([h,n])=>`<a href="${h}">${n}</a>`).join('')}</nav>${workspaceSourceMarkup()}<p id="workspace-notice" class="workspace-notice ${error?'is-error':''}" role="${error?'alert':'status'}">${e(notice)}</p><div class="workspace-layout ${overview?'is-overview':''}">${riverAxis()}${overview?'':`<section class="workspace-paper ${activeRiver?`river-tone-${activeRiver}`:''}">${draft?editor():comparing?comparison():item?detail(item):empty()}</section>`}</div></div></main>`;if(focus)document.querySelector('.workspace-paper h2')?.focus({preventScroll:true});}
function feedback(message,isError=true){notice=message;error=isError;const n=document.querySelector('#workspace-notice');n.textContent=message;n.classList.toggle('is-error',isError);if(isError&&draft)showFormError(document.querySelector('#workspace-form'),message);}
function capture(){if(!draft)return;const f=new FormData(document.querySelector('#workspace-form'));if(!milestoneOnly)for(const key of ['name','status','goal','notes',...(!isPlan?['river','support','gap','constraints','nextAction']:[])])draft[key]=String(f.get(key)??'');if(isPlan){if(!milestoneOnly){draft.river=String(f.get('river')??draft.river);const path=data.paths.find(p=>p.id===String(f.get('pathId')??''));if(f.get('pathId')!=='__keep__')draft.pathIds=path&&path.river===draft.river?[path.id]:[];draft.capitals=f.getAll('capitals');}for(const m of draft.milestones){if(!f.has(`m-name-${m.id}`))continue;m.name=String(f.get(`m-name-${m.id}`)||'');m.criterion=String(f.get(`m-criterion-${m.id}`)||'');const old=[...m.actions];m.actions=String(f.get(`m-actions-${m.id}`)||'').split('\n').map(x=>x.trim()).filter(Boolean).map(text=>{const i=old.findIndex(a=>a.text===text);return i<0?{id:newId(),text,done:false}:old.splice(i,1)[0];});}}}
function persist(result){const finish=r=>{if(!r.ok){feedback(r.error);return false;}data=r.data;return true;};const guarded=guardWorkspaceWrite(app,result);return guarded instanceof Promise?guarded.then(finish):finish(guarded);}function leave(){return !dirty||window.confirm('有尚未保存的修改，确定放弃吗？');}
function beginPath(river){overview=false;overviewSelection=false;milestoneOnly=null;draft=newPath();draft.river=river;dirty=false;comparing=false;render();}function beginPlan(id){milestoneOnly=null;const p=data.paths.find(x=>x.id===id);if(!p)return;overview=false;overviewSelection=false;draft=newPlan();draft.pathIds=[p.id];draft.river=p.river;dirty=false;openRivers.add(p.river);openPaths.add(p.id);render();}
app.addEventListener('click',ev=>{const t=ev.target.closest('[data-select]');if(!t||!dirty)return;if(!window.confirm('有尚未保存的修改，确定放弃吗？'))ev.stopImmediatePropagation();else dirty=false;},true);
app.addEventListener('change',ev=>{const t=ev.target;if(t.dataset.compare&&t.checked&&compareIds.length>=3){t.checked=false;feedback('一次最多比较三条路径。');ev.stopImmediatePropagation();}},true);
app.addEventListener('input',ev=>{if(ev.target.closest('#workspace-form')){dirty=true;capture();}});
app.addEventListener('change',async ev=>{const t=ev.target;if(t.closest('#workspace-form')){dirty=true;capture();}if(t.name==='pathId'||(isPlan&&t.name==='river')){render(false);return;}if(t.dataset.compare){compareIds=t.checked?[...compareIds,t.dataset.compare]:compareIds.filter(x=>x!==t.dataset.compare);render(false);return;}if(t.dataset.actionToggle||t.dataset.milestoneToggle){const item=structuredClone(data.plans.find(p=>p.id===selected)),m=item.milestones.find(m=>m.id===(t.dataset.milestone||t.dataset.milestoneToggle));if(t.dataset.actionToggle)m.actions.find(a=>a.id===t.dataset.actionToggle).done=t.checked;else m.done=t.checked;const saving=persist(workspaceConnection.saveItem(data,'plans',item));if(saving instanceof Promise?await saving:saving)feedback('完成状态已保存。',false);else t.checked=!t.checked;}});
app.addEventListener('submit',async ev=>{if(ev.target.id!=='workspace-form')return;ev.preventDefault();const showOverview=ev.submitter?.hasAttribute('data-save-overview')??false;capture();draft.name=draft.name.trim();const problem=validateWorkspaceDraft(kind,draft);if(problem){showFormError(ev.target,problem.message,problem.field);return;}const previous=data[kind].find(x=>x.id===draft.id);if(!isPlan&&previous&&previous.river!==draft.river&&data.plans.some(p=>p.pathIds.includes(draft.id))&&!window.confirm('移动路径后，其所属计划将随路径换河；跨河共享的旧计划会标为待归属。已确认的成果证明保持原样。继续吗？'))return;let r=guardWorkspaceWrite(app,workspaceConnection.saveItem(data,kind,draft));if(r instanceof Promise)r=await r;if(!r.ok){feedback(r.error);return;}data=r.data;selected=draft.id;openRivers.add(draft.river);if(isPlan)openPaths.add(draft.pathIds[0]);draft=null;milestoneOnly=null;dirty=false;if(showOverview){overview=true;overviewSelection=true;comparing=false;for(const river of Object.keys(riverNames))openRivers.add(river);if(isPlan)for(const path of data.paths)openPaths.add(path.id);}render();});
app.addEventListener('click',async ev=>{
 const t=ev.target.closest('button,a');if(!t)return;
 if(t.tagName==='A'){if(!leave())ev.preventDefault();return;}
 if(t.hasAttribute('data-collapse-detail')){overview=true;overviewSelection=true;for(const river of Object.keys(riverNames))openRivers.add(river);if(isPlan)for(const path of data.paths)openPaths.add(path.id);render();return;}
 if(t.hasAttribute('data-overview')){if(overview){overviewSelection=false;render();return;}if(!leave())return;overview=true;overviewSelection=false;draft=null;milestoneOnly=null;dirty=false;comparing=false;for(const river of Object.keys(riverNames))openRivers.add(river);if(isPlan)for(const path of data.paths)openPaths.add(path.id);render();return;}
 if(t.dataset.river){openRivers.has(t.dataset.river)?openRivers.delete(t.dataset.river):openRivers.add(t.dataset.river);render(false);return;}
 if(t.dataset.togglePath){openPaths.has(t.dataset.togglePath)?openPaths.delete(t.dataset.togglePath):openPaths.add(t.dataset.togglePath);render(false);return;}
 if(t.dataset.newPath){if(!leave())return;beginPath(t.dataset.newPath);return;}
 if(t.hasAttribute('data-create-plan')){if(!leave())return;overview=false;overviewSelection=false;selected=null;milestoneOnly=null;comparing=false;dirty=false;draft=data.paths.length?newPlan():null;if(draft)draft.river=data.paths[0].river;for(const river of Object.keys(riverNames))openRivers.add(river);render();return;}
 if(t.dataset.newPlan){if(!leave())return;beginPlan(t.dataset.newPlan);return;}
 if(t.dataset.select){overview=false;overviewSelection=false;selected=t.dataset.select;draft=null;milestoneOnly=null;dirty=false;comparing=false;render();return;}
 if(t.hasAttribute('data-edit')){draft=structuredClone(data[kind].find(x=>x.id===selected));milestoneOnly=null;if(isPlan&&!planPlacement(data,draft).ok)draft.pathIds=[];render();return;}
 if(t.dataset.editMilestone){draft=structuredClone(data.plans.find(x=>x.id===selected));milestoneOnly=t.dataset.editMilestone;dirty=false;render();return;}
 if(t.hasAttribute('data-add-detail')){draft=structuredClone(data.plans.find(x=>x.id===selected));const m=newMilestone();draft.milestones.push(m);milestoneOnly=m.id;dirty=true;render();return;}
 if(t.hasAttribute('data-cancel')){if(leave()){draft=null;dirty=false;render();}return;}
 if(t.hasAttribute('data-show-compare')){if(!leave())return;overview=false;overviewSelection=false;draft=null;dirty=false;comparing=true;render();return;}
 if(t.hasAttribute('data-close-compare')){comparing=false;render();return;}
 if(t.hasAttribute('data-delete')&&window.confirm(isPlan?'删除计划？成长记录会保留。':'删除路径？路径下计划会进入待归属区。')){const saving=persist(workspaceConnection.deleteRecord(data,kind,selected));if(saving instanceof Promise?await saving:saving){selected=data[kind][0]?.id??null;render();}return;}
 if(t.hasAttribute('data-add-milestone')||t.dataset.removeMilestone||t.dataset.up){capture();if(t.hasAttribute('data-add-milestone'))draft.milestones.push(newMilestone());if(t.dataset.removeMilestone&&window.confirm('移除里程碑及其行动？保存后解除成长记录的里程碑关联，原记录仍保留。'))draft.milestones=draft.milestones.filter(m=>m.id!==t.dataset.removeMilestone);if(t.dataset.up){const i=draft.milestones.findIndex(m=>m.id===t.dataset.up);if(i>0)[draft.milestones[i-1],draft.milestones[i]]=[draft.milestones[i],draft.milestones[i-1]];}if(milestoneOnly&&!draft.milestones.some(m=>m.id===milestoneOnly))milestoneOnly=null;dirty=true;render(false);}
});
window.addEventListener('beforeunload',ev=>{if(dirty){ev.preventDefault();ev.returnValue='';}});const hasItem=data[kind].some(x=>x.id===params.get('item'));if(hasItem)selected=params.get('item');if(!isPlan&&!hasItem&&params.get('new')==='1')beginPath(initialRiver);if(isPlan&&!hasItem&&data.paths.some(p=>p.id===params.get('path')))beginPlan(params.get('path'));render();
if(!isPlan&&params.get('direction')){
 const direction=explorationProfileConnection.readActive().profile.directions?.[params.get('direction')];
 const prepared=prepareDirectionPath(data,direction);
 if(prepared){openRivers.add(prepared.path.river);if(prepared.existing){selected=prepared.path.id;draft=null;notice='这条方向已有保存的路径，继续查看或编辑即可。';}else{draft=prepared.path;dirty=true;notice='已带入方向草稿。核对并点击保存后，才会建立长期路径。';}render();}
 else{notice='该方向暂时无法读取，请返回我的河检查。';error=true;render();}
}
